apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprovider-gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataprovider-gitlab
  template:
    metadata: 
      labels:
        app: dataprovider-gitlab
    spec:
      containers:
      - name: dataprovider-gitlab-container
        image: ulriksandberg/dataprovider:1.9
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dataprovider-gitlab-service
spec:
  selector:
    app: dataprovider-gitlab
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer